import Vue from 'vue'
import asyncComponents from './async-components-list' // this file will be autogenerated

export function asyncComponentImport (componentName) {
  if (Object.keys(asyncComponents).includes(componentName)) {
    return {
      [componentName]: async () => await asyncComponents[componentName]()
    }
  } else {
    console.error(`[ERROR in asyncImport]: wrong component name or typo in it (${componentName})`)
  }
}

/**
 * This function allows to make chunks smaller by checking if there are already components
 * in a bundle used inside async chunks
 * @param id
 * @returns {*}
 */

export function wiseImport (id) {
  if (Vue.options.components[id]) {
    return Vue.options.components[id]
  }


  if (id in asyncComponents) {
    Vue.component(id, async () => await asyncComponents[id]())

    return { [id]: Vue.options.components[id] }
  }
}
