const stores = require('../common/maps/stores')
const fs = require('fs')

fs.writeFile(
  'src/common/maps/autogenerated/multiple-lang-country.json',
  JSON.stringify(generateMultiLanguageCountryList(), null, 2),
  (err) => {
    if (err) throw err
  }
)

function generateMultiLanguageCountryList () {
  const locales = Object.keys(stores)
  let countriesWithMultipleLanguages = {}

  locales.forEach(key => {
    const currentCountryName = getCountryName(key)

    // second iteration to find locales with the same countries but different languages
    locales.forEach(innerKey => {
      const comparableCountryName = getCountryName(innerKey)

      // if keys are equals and country names are different then return
      if (key === innerKey || currentCountryName !== comparableCountryName) return
      // if countriesWithMultipleLanguages do not have property currentCountryName then create it
      if (!countriesWithMultipleLanguages[currentCountryName]) {
        countriesWithMultipleLanguages[currentCountryName] = {}
      }

      countriesWithMultipleLanguages[currentCountryName][key] = stores[key]
    })
  })

  return countriesWithMultipleLanguages
}

function getCountryName (locale) {
  return locale.split('-')[1]
}
